### ISSUE TITLE
No Config in 1.7.10

### ISSUE THREAD

**Issue by DarianLStephens** [BuiltBrokenModding/ComeCloser#3]
While I've tried a few methods of shutting the nametag off entirely before, this mod seems like the best of both worlds; having the nametag where appropriate, while keeping it from being unfair.
Unfortunately, the config doesn't seem to generate in 1.7.10, leaving the line-of-sight and distance completely unconfigurable.

**Comment by DarkGuardsman** [comment]
Its been a while since I looked at the code last, but the config should only generate server side. So check your server's config for the file. If it doesn't exist I'll check the mod here in the morning.

**Comment by DarianLStephens** [comment]
I have checked the server, my singleplayer instance.
Unless there's a specific folder for that when in singleplayer...?

**Comment by Hennamann** [comment]
I'm not sure the config generates at all in a singleplayer instance even if you open the game to LAN. At least not in the 1.7.10 version of the mod. I'll test it here and see if I can't get it fixed.

**Comment by Hennamann** [comment]
Alright, I changed the code to make the config generate clientside as well as server side should allow you to configure it for your LAN game. Here's a curseforge download for the build with the new fix: https://minecraft.curseforge.com/projects/come-closer/files/2539939

**Comment by DarkGuardsman** [comment]
Ya the mod was never made with LAN in mind. It was always made as a server-client system, but will work just as well in LAN with that change.

Also thanks @Hennamann for getting to that before I got to it, saved me some time :)
